### ISSUE TITLE
Plugin causes error

### ISSUE THREAD

**Issue by awrog** [wernerjoss/grav-plugin-icalendar#1]
Installed on new GRAV instance (1.6.9)
After install immediately get 
Whoops \ Exception \ ErrorException (E_NOTICE)
Array to string conversion

        $icsfile = (DATA_DIR . 'calendars/'.$this->config->get('plugins.icalendar.icsfile'));

When I hardcode it with 

        $icsfile = (DATA_DIR . 'calendars/keulen.ics');

I get new errors....

**Comment by ondrejvysek** [comment]
+1

**Comment by wernerjoss** [comment]
did you try
icsfile: keulen.ics
in your user/config/plugins/icalendar.yaml ?

**Comment by awrog** [comment]
Did a re-install en modified the icalendar.yaml as instructed above
That helped!

Also take into account that only future entries are shown

**Comment by wernerjoss** [comment]
ok, fine to see the problem solved :)

and yes, only future entries are shown, that is by intention.
