### ISSUE TITLE
Date Format Var?

### ISSUE THREAD

**Issue by thejame** [wernerjoss/grav-plugin-icalendar#2]
Might I suggest adding a date format variable? 
What I really want to do is return objects of the ICAL event that I can format and manipulate so I'm not just stuck in a list element. Any suggestions on how to do this?

**Comment by wernerjoss** [comment]
hm,
a date format variable could probably be introduced via icalendar.yaml ...
as for return of an object, that is IMO not possible with twig variables.
I'll have a closer look at this, however, soon.

**Comment by wernerjoss** [comment]
date format variable is now added - see updated Documentation.

**Comment by thejame** [comment]
Cool! Can you fix the Number of Events label? It says "Text Variable" on the plugin page - I think it's getting the label value from something that's not populated. 

![Capture](https://user-images.githubusercontent.com/6295224/60846226-9eeb5c80-a193-11e9-8559-3b940ce683af.PNG)

**Comment by wernerjoss** [comment]
ok, thanks for the hint 👍 
- I did not see this as I don't use the admin regularly...
should be fixed now, can you please just update your blueprints.yaml file from the repo and check ?

**Comment by thejame** [comment]
Yes that works (I updated mine manually as well). Thanks!
