### ISSUE TITLE
<li> tag not obeyed

### ISSUE THREAD

**Issue by awrog** [wernerjoss/grav-plugin-icalendar#3]
Glad I got the plugin working thanks to your help!
My page now contains:
```
Eventlist

<ol>
{{ eventlist() }} 
</ol>
```
But displays:

```
Eventlist
 
 <li>15.07.2019 - Meeting</li> <li>16.07.2019 - Meeting</li>
``` 

 
Generated by:
```
 <ol>
	&lt;li&gt;15.07.2019 - Meeting&lt;/li&gt;
	&lt;li&gt;16.07.2019 - Meeting&lt;/li&gt;
 
</ol>

```
Can I stop it from changing ```<li>``` into ```&lt;li&gt;``` ?

**Comment by wernerjoss** [comment]
did you enable twig processing in the page frontmatter ?
(see [docu](https://learn.getgrav.org/16/cookbook/twig-recipes) on that)

**Comment by awrog** [comment]
Yep, to no avail.

I need process Mardown, so I cannot turn that off
Switched Process Twig on / off, in combination with Process Twig first on /
off

tried a markdown unordered list and event-listing together in one page:

<ul>
<li>one</li>
<li>two </li>
<li>three</li>
</ul>


<ol>
&lt;li&gt;15.07.2019 - Meeting&lt;/li&gt;
&lt;li&gt;16.07.2019 - Meeting&lt;/li&gt;

</ol>

**Comment by wernerjoss** [comment]
what happens when you put {{ eventlist() }} in your page template ?
(e.g. default.html.twig)

**Comment by awrog** [comment]
Usually that fixes it. Not this time.
![Screenshot - 6_28_2019 , 09_19_06](https://user-images.githubusercontent.com/12153667/60324736-ded96500-9985-11e9-87a8-b95f227bf911.png)

**Comment by wernerjoss** [comment]
ok, so, this does not make a difference.
I'm now out of ideas, I guess.
the only thing I can think of is some file encoding issue.
maybe change encoding of the file EventListTwigExtension.class.php helps ?
or just put the `&lt;li&gt;` etc. in line 41 and 43 instead of `<li>` ?

**Comment by thejame** [comment]
What if you try this in your system.yaml file?

![Capture](https://user-images.githubusercontent.com/6295224/60848272-c98ce380-a19a-11e9-9588-c842a53d89b3.PNG)

**Comment by awrog** [comment]
@thejame Markdown entry looks the same (had to change extra to **true**)
No [change](https://lrp-netwerk.pkn.nl/test/typography-2) ....

**Comment by flo-bananzki** [comment]
It works for me with a workaround using the twig filter "raw".
I got the same Problem when I use Gantry5 Theme. (On Page-Content and as Custom HTML)
Try this:
`<ul>{{ eventlist()|raw }}</ul>`

**Comment by wernerjoss** [comment]
I'm closing this now as there were no more followup comments on the last workaround proposal.
feel free to open new issue if this still persists.
